//"use client"
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/Talal-Ahmed.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { motion } from "framer-motion";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
import WelcomeScreen from "@/components/WelcomeScreen";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import ParticlesContainer from "@/components/ParticlesContainer";

export default function Home() {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const hasVisitedBefore = sessionStorage.getItem("hasVisited");
    if (!hasVisitedBefore) {
      // If the user has not visited before during this session, show the welcome screen
      setIsLoading(true);
      sessionStorage.setItem("hasVisited", "true");
    }
  }, []); // Only run on initial mount

  const handleWelcomeScreenFinish = () => {
    setIsLoading(false);
  };

  return (
    <>
      <Head>
        <title>Talal Ahmed</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {isLoading && isHome ? (
        <WelcomeScreen finishLoading={handleWelcomeScreenFinish} />
      ) : (
        <>
          <TransitionEffect />
          <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
            <Layout className="pt-0 md:pt-16 sm:pt-8">
            <ParticlesContainer />
              <div className="flex items-center justify-between w-full lg:flex-col">
                <motion.div
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 1.9 }}
                  className="relative w-1/2 rounded-full shadow-lg shadow-dark bg-primary dark:bg-primaryDark md:w-full overflow-hidden"
                >
                  {/* Wavy effect */}
                  <div className="absolute top-0 left-0 right-0">
                    <svg
                      viewBox="0 0 1440 320"
                      xmlns="http://www.w3.org/2000/svg"
                      className="fill-current opacity-0"
                    >
                      <path
                        fillOpacity="1"
                        d="M0,128L120,138.7C240,149,480,171,720,144C960,117,1200,139,1320,149.3L1440,160L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"
                      ></path>
                    </svg>
                  </div>

                  {/* Image */}
                  <motion.div
                    initial={{ opacity: 0, y: 100 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 2.4 }}
                    className="relative z-10"
                  >
                    <Image
                      src={profilePic}
                      alt="Talal Ahmed"
                      className="w-full h-auto shadow-1 rounded-full lg:hidden md:inline-block md:w-full"
                      priority
                      sizes="(max-width:768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                    />
                  </motion.div>
                </motion.div>
                <div className="w-1/2 pl-3 flex flex-col items-center self-center lg:w-full lg:text-center">
                  <AnimatedText
                    text="Turning Vision Into Reality With Code And Design."
                    className="!text-6xl !text-left 
                    xl:!text-5xl lg:!text-center lg:!text-5xl sm:!text-3xl"
                  />
                  <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                    As a skilled Web developer, I am dedicated to turning
                    ideas into innovative web applications. Explore my latest
                    projects and articles, showcasing my expertise in React.js, Next.js
                    and web development.
                  </p>
                  <div className="flex items-center self-start mt-2 lg:self-center">
                    <Link
                      href="/Talal-Ahmed.pdf"
                      target={"_blank"}
                      className="flex focus:ring-4 shadow-lg focus:ring-primary dark:focus:ring-primaryDark transform active:scale-75 transition-transform items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                      dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                      hover:dark:border-light md:p-2 md:px-4 md:text-base"
                      download={true}
                    >
                      Resume <LinkArrow className={"w-6 ml-1"} />
                    </Link>
                    <Link
                      href="mailto:abc@gmail.com"
                      target={"_blank"}
                      className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                    >
                      Contact
                    </Link>
                  </div>
                </div>
              </div>
            </Layout>

            <HireMe />
            <div className="absolute right-8 -bottom-5 inline-block w-24 md:hidden">
              <Image
                src={lightBulb}
                alt="Talal Ahmed"
                className="w-full h-auto"
              />
            </div>
          </main>
        </>
      )}
    </>
  );
}

// "use client"
// import Layout from '@/components/Layout'
// import Head from 'next/head'
// import Image from 'next/image'
// import profilePic from "../../public/images/profile/Talal-Ahmed.png"
// import AnimatedText from '@/components/AnimatedText'
// import Link from 'next/link'
// import { LinkArrow } from '@/components/Icons'
// import HireMe from '@/components/HireMe'
// import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
// import TransitionEffect from '@/components/TransitionEffect'
// import WelcomeScreen from '@/components/WelcomeScreen'
// import { usePathname } from 'next/navigation'
// import { path } from "animejs"
// import { useEffect, useState } from 'react'

// export default function Home() {
//   const pathname = usePathname()
//   const isHome = pathname === "/"
//   const [isLoading, setIsLoading] = useState(isHome)

//   useEffect(() => {
//     if(isLoading) return
//   },[isLoading])

//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//       </Head>
//       {isLoading && isHome ? (<WelcomeScreen finishLoading={() => setIsLoading(false)}/>) : (<>
//       <TransitionEffect />
//       <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
//         <Layout className='pt-0 md:pt-16 sm:pt-8'>
//           <div className='flex items-center justify-between w-full lg:flex-col'>
//             <div className='w-1/2 rounded-full bg-primary dark:bg-primaryDark md:w-full'>
//               <Image src={profilePic} alt='Talal Ahmed' className='w-full h-auto rounded-full lg:hidden md:inline-block md:w-full'
//               priority
//               sizes="(max-width:768px) 100vw,
//               (max-width: 1200px) 50vw,
//               50vw"
//               />
//             </div>
//             <div className='w-1/2 pl-3 flex flex-col items-center self-center lg:w-full lg:text-center'>
//               <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left
//               xl:!text-5xl lg:!text-center lg:!text-5xl sm:!text-3xl
//               ' />
//               <p className='my-4 text-base font-medium md:text-sm sm:text-xs'> As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
//                 Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
//                 <div className='flex items-center self-start mt-2 lg:self-center'>
//                   <Link href="/Talal-Ahmed.pdf" target={"_blank"}
//                   className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
//                   dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
//                   hover:dark:border-light md:p-2 md:px-4 md:text-base
//                   "
//                   download={true}
//                   >Resume <LinkArrow className={"w-6 ml-1"} />
//                   </Link>
//                   <Link href="mailto:abc@gmail.com" target={"_blank"}
//                   className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
//                   >Contact</Link>
//                 </div>
//             </div>
//           </div>
//         </Layout>

//         <HireMe />
//         <div className='absolute right-8 -bottom-5 inline-block w-24 md:hidden'>
//           <Image src={lightBulb} alt="Talal Ahmed" className='w-full h-auto' />
//         </div>
//       </main>
//       </>
//       )}

//     </>
//   )
// }
